#pragma once

#define LIBGTPNL_VERSION {{VERSION}}
#define LIBGTPNL_VERSION_STR "{{VERSION}}"

#define LIBGTPNL_VERSION_MAJOR {{VERSION_MAJOR}}
#define LIBGTPNL_VERSION_MINOR {{VERSION_MINOR}}
#define LIBGTPNL_VERSION_PATCH {{VERSION_PATCH}}

#define LIBGTPNL_VERSION_GREATER_EQUAL(major, minor, patch) \
	(LIBGTPNL_VERSION_MAJOR > (major) || \
	 (LIBGTPNL_VERSION_MAJOR == (major) && \
	  LIBGTPNL_VERSION_MINOR > (minor)) || \
	 (LIBGTPNL_VERSION_MAJOR == (major) && \
	  LIBGTPNL_VERSION_MINOR == (minor) && \
	  LIBGTPNL_VERSION_PATCH >= (patch)))
